var japname = {
    "魔女を救え！": "Cloris",
    "魔女の娘": "Belinda",
    "闇の忍者軍団": "Azami",
    "鬼を宿す剣士": "Momiji",
    "聖戦士の挑戦": "Maribel",
    "影の狙撃手": "Rita",
    "魔人の宿命": "Fran",
    "戦乙女の契約": "Emilia",
    "暗黒騎士団の脅威": "Yurina",
    "暗黒舞踏会": "Waltz",
    "魔術の秘法": "Odette",
    "アンナと雪の美女": "Eliza",
    "山賊王への道": "Rorone",
    "竜騎士の誓い": "Lucille",
    "錬金術士と賢者の石": "Corin",
    "モンクの修行場": "Lin",
    "聖鎚闘士の挑戦": "Miranda",
    "鬼招きの巫女": "Shiho",
    "砲科学校の訓練生": "Kanon",
    "囚われの魔法剣士": "Charlotte",
    "死霊の船と提督の決意": "Reanbell",
    "帝国の天馬騎士": "Isabelle",
    "暗黒騎士団と狙われた癒し手": "Yuno",
    "獣人の誇り": "Ada",
    "白の帝国と偽りの都市": "Lieselotte",
    "堕天使の封印": "Chloe",
    "暗黒騎士団と聖夜の贈り物": "Sarasa",
    "古代の機甲兵": "Rikka",
    "呪術師と妖魔の女王": "Revy",
    "私掠船長と魔の海域": "Sabrina",
    "ヴァンパイアと聖なる復讐者": "Rumaria",
    "妖魔の女王と戦術の天才": "Helena",
    "魔界蟻と囚われた男達": "Jake / Oscar",
    "天使たちの陰謀": "Sereina",
    "魔蝿の森と呪われた番人": "Aida",
    "失われた竜の島": "Ignis",
    "帝国神官の帰還": "Lucia",
    "闇の組織と狙われた王子": "Seven",
    "オーク格闘家の王子軍入門": "Bestla",
    "王子軍の夏祭り": "Phyllis (Yukata)",
    "カリオペと恐怖の夜": "Calliope (Dress)",
    "夢現のダークプリースト": "Psyche",
    "魔王軍の胎動": "Linaria",
    "彷徨える守護の盾": "Saris",
    "渚に咲きし水着騎兵": "Carrie (Swimsuit)",
    "カボチャの国の魔法使い": "Candy",
    "星に祈りし聖夜の癒し手": "Camilla (Christmas)",
    "学園騎兵科の新入生": "Mischa (School)",
    "白き獣人と闇の組織": "Fluffy",
    "砂浜を駆ける魔術師": "Maya (Swimsuit)",
    "密林のハロウィンパーティー": "Renarde (Halloween)",
    "デーモンサンタのおもちゃ工場": "Ertel (Christmas)"
}
exports.japname = japname;
