var ulist = [
          "Cloris",
          "Belinda",
          "Azami",
          "Momiji",
          "Maribel",
          "Rita",
          "Fran",
          "Emilia",
          "Yurina",
          "Waltz",
          "Odette",
          "Eliza",
          "Rorone",
          "Lucille",
          "Corin",
          "Lin",
          "Miranda",
          "Shiho",
          "Kanon",
          "Charlotte",
          "Reanbell",
          "Isabelle",
          "Yuno",
          "Ada",
          "Lieselotte",
          "Chloe",
          "Sarasa",
          "Rikka",
          "Revy",
          "Sabrina",
          "Rumaria",
          "Helena",
          "Jake / Oscar",
          "Oscar",
          "Jake",
          "Sereina",
          "Aida",
          "Ignis",
          "Lucia",
          "Seven",
          "Bestla",
          "Phyllis (Yukata)",
          "Calliope (Dress)",
          "Psyche",
          "Linaria",
          "Saris",
          "Carrie (Swimsuit)",
          "Candy",
          "Camilla (Christmas)",
          "Mischa (School)",
          "Fluffy"
        ]
exports.ulist = ulist;
