var unum = {
          "Cloris": 1,
          "Belinda": 2,
          "Azami": 3,
          "Momiji": 4,
          "Maribel": 5,
          "Rita": 6,
          "Fran": 7,
          "Emilia": 8,
          "Yurina": 9,
          "Waltz": 10,
          "Odette": 11,
          "Eliza": 12,
          "Rorone": 13,
          "Lucille": 14,
          "Corin": 15,
          "Lin": 16,
          "Miranda": 17,
          "Shiho": 18,
          "Kanon": 19,
          "Charlotte": 20,
          "Reanbell": 21,
          "Isabelle": 22,
          "Yuno" : 23,
          "Ada": 24,
          "Lieselotte": 25,
          "Chloe": 26,
          "Sarasa": 27,
          "Rikka": 28,
          "Revy": 29,
          "Sabrina": 30,
          "Rumaria": 31,
          "Helena": 32,
          "Jake / Oscar": 33,
          "Oscar": 34,
          "Jake": 35,
          "Sereina":36,
          "Aida": 37,
          "Ignis": 38,
          "Lucia": 39,
          "Seven": 40,
          "Bestla": 41,
          "Phyllis (Yukata)": 42,
          "Calliope (Dress)": 43,
          "Psyche": 44,
          "Linaria": 45,
          "Saris": 46,
          "Carrie (Swimsuit)": 47,
          "Candy" : 48,
          "Camilla (Christmas)": 49,
          "Mischa (School)": 50,
          "Fluffy": 51,
          "Maya (Swimsuit)": 52,
		"Renarde (Halloween)": 53,
		"Ertel (Christmas)" : 54
        }
exports.unum = unum;
