var unum = {
    "Cloris": 1,
    "Belinda": 2,
    "Azami": 3,
    "Momiji": 4,
    "Maribel": 5,
    "Rita": 6,
    "Fran": 7,
    "Emilia": 8,
    "Yurina": 9,
    "Waltz": 10,
    "Odette": 11,
    "Eliza": 12,
    "Rorone": 13,
    "Lucille": 14,
    "Corin": 15,
    "Lin": 16,
    "Miranda": 17,
    "Shiho": 18,
    "Kanon": 19,
    "Charlotte": 20,
    "Reanbell": 21,
    "Isabelle": 22,
    "Yuno": 23,
    "Ada": 24,
    "Lieselotte": 25,
    "Chloe": 26,
    "Sarasa": 27,
    "Rikka": 28,
    "Revy": 29,
    "Sabrina": 30,
    "Rumaria": 31,
    "Helena": 32,
    "Jake / Oscar": 33,
    "Oscar": 33,
    "Jake": 33,
    "Sereina": 34,
    "Aida": 35,
    "Ignis": 36,
    "Lucia": 37,
    "Seven": 38,
    "Bestla": 39,
    "Phyllis (Yukata)": 40,
    "Calliope (Dress)": 41,
    "Psyche": 42,
    "Linaria": 43,
    "Saris": 44,
    "Carrie (Swimsuit)": 45,
    "Candy": 46,
    "Camilla (Christmas)": 47,
    "Mischa (School)": 48,
    "Fluffy": 49,
    "Maya (Swimsuit)": 50,
    "Renarde (Halloween)": 51,
    "Ertel (Christmas)": 52
}
exports.unum = unum;
