var list = ['Rogues', 
            'Soma (New Year\'s)', 
            'Tigre', 
            'Renarde', 
            'Bella', 
            'Cloris', 
            'Azami', 
            'Hyuna', 
            'Amy',
            'Mikoto', 
            'Elva', 
            'Sakuya', 
            'Raven', 
            'Ada', 
            'Berna', 
            'Chibi Berna', 
            'Junon', 
            'Junon (New Year\'s)', 
            'Ashera', 
            'Eldora', 
            'Ballad', 
            'Benibotan',
            'Betty', 
            'Cecily', 
            'Chibi Cecily', 
            'Cypria', 
            'Cypria (Christmas)', 
            'Eric', 
            'Harissa', 
            'Kagerou', 
            'Koharu', 
            'Len', 
            'Lepuru',
            'Lulu', 
            'Marika', 
            'Minerva', 
            'Motley',
            'Nendoroid Sybilla', 
            'Patel', 
            'Prisna',
            'Renarde (Halloween)', 
            'Risley',
            'Rita (Swimsuit)', 
            'Roza', 
            'Saki', 
            'Seven', 
            'Sybilla', 
            'Viktor', 
            'Wonder Heart',
            'Xiao',
			'Bearca'
			];

exports.list = list;
