var list = ['Curse Users', 
           'Maou\'s Bodyguards', 
           'Nekomata', 
           'Playwrights (GBM)', 
           'Puppet Dolls 【Fuukan】', 
		   'Detective (GBM)',
           'Orochihime', 
           'Prince (Dark)', 
           'Sybilla', 
           'Yurina', 
           'Chibi Cornelia', 
           'Cornelia (Christmas)', 
           'Cornelia', 
           'Dark Knight', 
           'Ban', 
           'Tamami', 
           'Aida', 
           'Hilde', 
           'Hu Ximei', 
           'Puniru', 
           'Erlang Shen', 
           'Shinomiya Komachi', 
           'Isambard',
           'Aira',
		   'Grimoire',
		   'Tsumuji'
           ];

exports.list = list;
