var list = ['Armor Maids (Maids)', 
            'Caravan Masters (Merchants)', 
            'Hermits', 
            'Sly and Cunning Genius 【Koihime】', 
            'Evil Seekers (Evil Princesses)', 
			'Principals (Dancers)',
            'Rosalie', 
            'Kagerou', 
            'Khuri', 
            'Thetis', 
            'Roana', 
            'Erenia', 
            'Mordiberte', 
            'Karin', 
            'Wendy', 
            'Kibahime', 
            'Racua', 
            'Ban', 
            'Holly', 
            'Zilva', 
            'Khuri (Swimsuit)', 
            'Farne (Bride)', 
            'Lateria', 
            'Sophie (Valentine\'s)', 
            'Lychnos', 
            'Miruno', 
            'Miruno (Swimsuit)', 
            'Jacqueline', 
            'Kuuko', 
            'Orochihime (New Year\'s)', 
            'Alice (Valentine\'s)', 
            'Lilia', 
            'Rovinia', 
            'Shade', 
            'Lina', 
            'Augusta',
            'Shushu (Hot Springs)',
			'Bearca'
           ];

exports.list = list;
