var list = ['Tengu', 
            '8-Gates Feng Shui Instructors (Feng Shui Users)', 
            'Nurarihyon', 
            'Shadow Hunters (Vampire Hunters)', 
            'Visionaries (Shamans)', 
            'Amelie', 
            'Kurama', 
            'Fiore', 
            'Ariel', 
            'Hatsune', 
            'Juubei', 
            'Orihime', 
            'Prim', 
            'Prisna', 
            'Ricola', 
            'Rita', 
            'Rita (Swimsuit)', 
            'Rovinia', 
            'Sagiri', 
            'Setsuna', 
            'Shiro',
            'Supura', 
            'Tsugumi',
            'Xenia',
            'Druids\' Tokens',
            'Katrina\'s Tokens'
           ];

exports.list = list;
