var bannersil = {
    1 : 'Mortimer',
    2 : 'Christopher',
    3 : 'Giovanni',
    4 : 'Palace',
    5 : 'Asar',
	6 : 'Ballad',
	7 : 'Khuri',
	8 : 'Percis',
	9 : 'Dan',
	10 : 'Niel',
	11 : 'Ertel',
	12 : 'Kazuha',
	13 : 'Saizou',
	14 : 'Iroha',
	15 : 'Rozette',
	16 : 'Cassis',
	17 : 'Sharon',
	18 : 'Merone',
	19 : 'Thelma',
	20 : 'Danan',
	21 : 'Renarde',
	22 : 'Tigre',
	23 : 'Maya',
	24 : 'Nicholaus',
	25 : 'Mao',
	26 : 'Miguel',
	27 : 'Fei',
	28 : 'Riele',
	29 : 'Sharqi',
	30 : 'Picky'
}

exports.bannersil = bannersil;
