var eventblack = [
    	'Anya',
    	'Saki',
    	'Karma (Black)',
    	'Anna',
    	'Liana',
	'Nagi',
	'Eterna',
	'Metus',
	'Reshia',
	'Hibari',
	'Shino',
	'White Emperor',
	'Anna (Swimsuit)',
	'Hakunokami',
	'Anatolia',
	'Saval',
	'Farne (Bride)',
	'Noire',
	'Shadia',
	'Berna (Bride)',
	'Anna (Idol)',
	'Anna (Uniform)',
	'Dark Knight',
	'Cynthia',
	'Xing-Fu',
	'Anna (Waitress)',
	'Atnates (Black)',
	'Nicole',
	'Diera (Bride)'
]

exports.eventblack = eventblack;
