var eventgold = [
    	'Cloris',
    	'Aria',
    	'Noel',
    	'Soma (New Year\'s)',
    	'Marie',
	'Xiao',
	'Erun',
	'Abel',
	'Zaram',
	'Boris',
	'Goliah',
	'Erun',
	'Phyllis (Yukata)',
	'Daniela (Yukata)',
	'Katie',
	'Calliope (Dress)',
	'Iris (New Year\'s)',
	'Leeanne (New Year\'s)',
	'Guren',
	'Hien',
	'Mitra',
	'Rozette (New Year\'s)',
	'Mischa (School)',
	'Viktor',
	'Maya (Swimsuit)',
	'Raichi',
	'Giovanni (School)',
	'Maurette',
	'Ryuryu',
	'Mao (Yukata)',
	'Renarde (Halloween)',
	'Ertel (Christmas)',
	'Sharqi (Valentine\'s)'
]

exports.eventgold = eventgold;
