var eventgold = {
    1 : 'Cloris',
    2 : 'Aria',
    3 : 'Noel',
    4 : 'Chloe',
    5 : 'Marie',
	6 : 'Xiao',
	7 : 'Erun',
	8 : 'Abel',
	9 : 'Zaram',
	10 : 'Boris',
	11 : 'Goliah',
	12 : 'Erun',
	13 : 'Phyllis (Yukata)',
	14 : 'Daniela (Yukata)',
	15 : 'Katie',
	16 : 'Calliope (Dress)',
	17 : 'Iris (New Year\'s)',
	18 : 'Leeanne (New Year\'s)',
	19 : 'Guren',
	20 : 'Hien',
	21 : 'Mitra',
	22 : 'Rozette (New Year\'s)',
	23 : 'Mischa (School)',
	24 : 'Viktor',
	25 : 'Maya (Swimsuit)',
	26 : 'Raichi',
	27 : 'Giovanni (School)',
	28 : 'Maurette',
	29 : 'Ryuryu',
	30 : 'Soma (New Year\'s)'
}

exports.eventgold = eventgold;
