var eventblack = {
    1 : 'Anya',
    2 : 'Saki',
    3 : 'Karma (Black)',
    4 : 'Anna',
    5 : 'Liana',
	6 : 'Nagi',
	7 : 'Eterna',
	8 : 'Metus',
	9 : 'Reshia',
	10 : 'Hibari',
	11 : 'Shino',
	12 : 'White Emperor',
	13 : 'Anna (Swimsuit)',
	14 : 'Hakunokami',
	15 : 'Anatolia',
	16 : 'Saval',
	17 : 'Farne (Bride)',
	18 : 'Noire',
	19 : 'Shadia',
	20 : 'Berna (Bride)',
	21 : 'Anna (Idol)',
	22 : 'Anna (Uniform)',
	23 : 'Dark Knight',
	24 : 'Cynthia',
	25 : 'Xing-Fu',
	26 : 'Anna (Waitress)',
	27 : 'Atnates (Black)'
}

exports.eventblack = eventblack;
